// graphql/client_react/src/components/Authors.js
import React, {Component} from 'react';

import AuthorList from './AuthorList';
import CreateAuthor from './CreateAuthor';

class Authors extends Component {
    render() {
        return (
            <div>
                <AuthorList/>
                <CreateAuthor/>
            </div>
        );
    }
}

export default Authors;

// graphql/client_vue/src/components/Authors.vue
<template>
    <div>
        <AuthorList/>
        <CreateAuthor/>
    </div>
</template>


<script>
    import AuthorList from './AuthorList';
    import CreateAuthor from './CreateAuthor';

    export default {
        name: 'Authors',

        components: {
            AuthorList,
            CreateAuthor
        }
    }
</script>

<style scoped></style>
